# Generated by Django 5.0.6 on 2024-07-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_user_profile_picture_student_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='teacher_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.teacher')),
            ],
        ),
    ]
