# Generated by Django 5.0.7 on 2024-08-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_teacherfile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classroom", options={"ordering": ["class_no"]},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["roll_no"],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.RemoveField(model_name="teacher", name="subject",),
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.ManyToManyField(blank=True, to="main.subject"),
        ),
    ]
