# Generated by Django 5.0.7 on 2024-08-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="attendance", unique_together=set(),),
    ]
